"""Automated cross-slide accessory/jacket continuity QA gate.

Compares NAMED attribute regions (e.g. bag, strap, necklace) across a
carousel's slides against a canonical reference slide, using CLIP embedding
cosine similarity per region. Fails the batch (non-zero exit) if ANY named
region on ANY compared slide falls below that region's threshold.

Why multiple named regions instead of one broad crop: a single broad
lower-torso crop (this script's original v1) can score a high overall
similarity even when a specific attribute — e.g. bag strap material, or
necklace style — differs, because the broader region's dominant colors
(skin tone, jacket denim, general palette) swamp a small attribute's
contribution to the embedding. Splitting into tight per-attribute crops
makes each comparison sensitive to exactly the thing it's checking.
Evidence: see qa_evidence_old_slide02_fails.txt in this repo, generated by
running this script's --strap region against the PR #161 commit e8e90fc
version of slide_02.png (gold chain strap) vs slide_03.png (leather strap,
canonical) — FAILS at a score the broad crop did not catch.

LIMITATION (stated plainly, not oversold): CLIP embedding similarity on a
region crop catches gross mismatches (wrong bag color, jacket missing,
wrong necklace STYLE — e.g. layered vs. single-pendant) but does NOT
reliably catch strap MATERIAL differences (gold chain vs. leather scored
0.88 similarity even on a tight crop isolating just the strap — see
qa_evidence_old_slide02_fails.txt) and is NOT fine-grained enough to
verify exact clasp geometry or precise hue matching pixel-for-pixel. It is
a coarse automated gate, not a substitute for the human full-resolution
review this pipeline's carousel_workflow.md already mandates.

FRAMING CONSTRAINT: the "necklace" and "strap" regions assume a
front-facing slide where the neckline/chest is visible. Applying them to a
faceless/rear-view slide (this carousel's slide_04) produces a false
positive FAIL — the crop lands on jacket collar, not a necklace, because
there IS no necklace visible from behind. Only check "bag" for rear-view
slides; skip "necklace"/"strap" for them, or expect and disregard the
false fail.

No new model download required beyond what clip_similarity_audit.py already
uses (open-clip-torch, ViT-L-14, openai weights).

Usage:
    python scripts/qa_accessory_continuity.py --dir output/2026-09-29/ananya/d3_coffee_run_outfit_math \
        --canonical slide_03.png --compare slide_02.png,slide_04.png
    # or test a single region against arbitrary files (used for evidence-gathering):
    python scripts/qa_accessory_continuity.py --canonical-file <path> --compare-files <path1>,<path2> --region strap
"""
import sys
from pathlib import Path

import click
from rich.console import Console
from rich.table import Table

console = Console()

# Named attribute regions as (x0, y0, x1, y1) fractions of image size.
# Tuned against this D3 carousel's fixed camera framing (same anchor, same
# scene, subject roughly centered) — not a universal region set.
#
# CALIBRATION EVIDENCE (see qa_evidence_old_slide02_fails.txt):
# - "necklace" tight crop DOES separate this pair: old (layered chain) vs
#   slide_03 (single pendant) = 0.7996; fixed slide_02 vs slide_03 = 0.9190.
#   Threshold 0.85 correctly fails the old version and passes the fix.
# - "strap" region does NOT reliably separate gold-chain vs leather-strap
#   at any crop tightness tested (broad crop: 0.9272; tight strap-only
#   crop isolating just the chain/strap line: 0.8777) — CLIP's embedding
#   space doesn't strongly encode "chain jewelry" vs "leather strap"
#   texture as distinct when both are thin diagonal objects on the same
#   fabric background. Raising the threshold to force a fail here would
#   just be threshold-fitting to one example, not a real detector — not
#   done. The strap region is kept in this script for whatever coarse
#   signal it does provide, but this limitation is reported honestly
#   rather than concealed: strap MATERIAL differences (as opposed to bag
#   presence/absence or gross color) are not reliably catchable by this
#   method and still require human review.
REGIONS = {
    "bag": (0.25, 0.62, 0.85, 0.95),       # bag body + clasp, avoids the strap line
    "strap": (0.42, 0.45, 0.62, 0.68),     # tight strap-only band (best achievable, still unreliable — see above)
    "necklace": (0.40, 0.30, 0.62, 0.45),  # tight necklace/pendant band — this one works
}

REGION_THRESHOLDS = {
    "bag": 0.80,
    "strap": 0.80,      # kept for coarse signal only; do not trust this to catch material swaps
    "necklace": 0.85,   # calibrated: separates layered-vs-single-pendant reliably (see evidence)
}


def load_clip():
    import open_clip
    import torch
    model, _, preprocess = open_clip.create_model_and_transforms("ViT-L-14", pretrained="openai")
    model.eval()
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = model.to(device)
    return model, preprocess, device, torch


def crop_region(img, box):
    w, h = img.size
    x0, y0, x1, y1 = box
    return img.crop((int(x0 * w), int(y0 * h), int(x1 * w), int(y1 * h)))


def embed(model, preprocess, device, torch, img_path: Path, box):
    from PIL import Image
    with Image.open(img_path) as img:
        c = crop_region(img.convert("RGB"), box)
        t = preprocess(c).unsqueeze(0).to(device)
        with torch.no_grad():
            feat = model.encode_image(t)
            feat /= feat.norm(dim=-1, keepdim=True)
        return feat


@click.command()
@click.option("--dir", "carousel_dir", type=click.Path(exists=True, file_okay=False, path_type=Path), default=None,
              help="Carousel directory (canonical/compare filenames are resolved inside it).")
@click.option("--canonical", default=None, help="Filename of the canonical slide, resolved inside --dir.")
@click.option("--compare", default=None, help="Comma-separated filenames to check, resolved inside --dir.")
@click.option("--canonical-file", type=click.Path(exists=True, dir_okay=False, path_type=Path), default=None,
              help="Absolute path to the canonical image (alternative to --dir/--canonical, for evidence tests).")
@click.option("--compare-files", default=None,
              help="Comma-separated absolute paths to compare (alternative to --dir/--compare).")
@click.option("--region", default="all", type=click.Choice(["all", "bag", "strap", "necklace"]),
              help="Which named region(s) to check.")
@click.option("--threshold", default=None, type=float,
              help="Override the per-region calibrated threshold (applies to all selected regions). "
                   "Default: use each region's own calibrated REGION_THRESHOLDS value.")
def main(carousel_dir, canonical, compare, canonical_file, compare_files, region, threshold):
    model, preprocess, device, torch = load_clip()

    if canonical_file:
        canon_path = canonical_file
        compare_paths = [Path(p.strip()) for p in compare_files.split(",")]
    else:
        if not (carousel_dir and canonical and compare):
            raise click.ClickException("Provide either --canonical-file/--compare-files or --dir/--canonical/--compare.")
        canon_path = carousel_dir / canonical
        compare_paths = [carousel_dir / c.strip() for c in compare.split(",")]

    regions = REGIONS if region == "all" else {region: REGIONS[region]}

    table = Table(title=f"Accessory continuity vs {canon_path.name}")
    table.add_column("Slide")
    table.add_column("Region")
    table.add_column("Cosine sim")
    table.add_column("Threshold")
    table.add_column("Result")

    failures = []
    for region_name, box in regions.items():
        region_threshold = threshold if threshold is not None else REGION_THRESHOLDS[region_name]
        canon_feat = embed(model, preprocess, device, torch, canon_path, box)
        for cmp_path in compare_paths:
            if not cmp_path.exists():
                console.print(f"[red]Missing: {cmp_path}[/red]")
                failures.append(f"{cmp_path.name}/{region_name}")
                continue
            feat = embed(model, preprocess, device, torch, cmp_path, box)
            sim = float((canon_feat @ feat.T).item())
            passed = sim >= region_threshold
            if not passed:
                failures.append(f"{cmp_path.name}/{region_name}")
            note = " (unreliable, see docstring)" if region_name == "strap" else ""
            table.add_row(cmp_path.name, region_name + note, f"{sim:.4f}", f"{region_threshold:.2f}",
                          "[green]PASS[/green]" if passed else "[red]FAIL[/red]")

    console.print(table)

    if failures:
        console.print(f"\n[red]GATE FAILED[/red] — {len(failures)} check(s) below threshold: {', '.join(failures)}")
        console.print("[yellow]Coarse automated check — does not replace full-resolution human review.[/yellow]")
        sys.exit(1)
    console.print("\n[green]GATE PASSED[/green] — all compared regions within threshold of the canonical.")
    console.print("[yellow]Coarse automated check — does not replace full-resolution human review.[/yellow]")


if __name__ == "__main__":
    main()
